-- OBSOLETO: sys_sucursal ahora se crea directamente en db/postgresql/01_schema.sql
-- (con empresa INTEGER en vez de VARCHAR(30), ver MIGRACION_BITACORA.md).
-- Este archivo se conserva solo como referencia histórica; no ejecutar contra una
-- base nueva ni contra la base actual.
