export const MODULES = [
  {
    id: 'contabilidad',
    label: 'Contabilidad',
    icon: 'fa-solid fa-book-open',
    menu: [],
  },
  {
    id: 'sueldos',
    label: 'Sueldos',
    icon: 'fa-solid fa-briefcase',
    menu: [
      {
        label: 'Empleados',
        icon: 'fa-solid fa-users',
        items: [
          { label: 'Empleados activos', icon: 'fa-solid fa-user', path: '/sueldos/empleados' },
          { label: 'Empleados inactivos', icon: 'fa-solid fa-user-slash', path: '/sueldos/empleados?estado=inactivo' },
        ],
      },
      {
        label: 'Conceptos',
        icon: 'fa-solid fa-tags',
        items: [
          { label: 'Concepto' },
          { label: 'Listado de conceptos' },
          { separator: true },
          { label: 'Fórmula' },
          { label: 'Listado de fórmulas' },
          { separator: true },
          { label: 'Grupo de Conceptos' },
          { label: 'Listado de grupos de conceptos' },
          { label: 'Grupo General de Conceptos' },
          { label: 'Clases de Concepto' },
          { separator: true },
          { label: 'Tabla' },
          { label: 'Tipo de Tabla' },
        ],
      },
      {
        label: 'Liquidaciones',
        icon: 'fa-solid fa-calculator',
        items: [
          { label: 'Liquidación' },
          { label: 'Recibo' },
          { label: 'Recibos Automáticos' },
          { label: 'Recibos Recalculados' },
          { separator: true },
          { label: 'Listado de recibos' },
          { label: 'Listado de contribuciones' },
          { label: 'Listado de auxiliares' },
          { separator: true },
          { label: 'Eliminación masiva' },
        ],
      },
      {
        label: 'Novedades',
        icon: 'fa-solid fa-bell',
        items: [
          { label: 'Novedad' },
          { label: 'Listado de novedades' },
          { separator: true },
          { label: 'Novedades por Tabla' },
          { label: 'Novedades Secuenciales' },
          { label: 'Novedades Automáticas' },
          { separator: true },
          { label: 'Tipo de Novedad' },
          { label: 'Eliminar novedades' },
        ],
      },
      {
        label: 'Historial',
        icon: 'fa-solid fa-clock-rotate-left',
        items: [
          { label: 'Historial' },
          { label: 'Listado de historiales' },
          { separator: true },
          { label: 'Historial de Empleado' },
          { label: 'Listado de historiales de empleados' },
          { label: 'Historiales Automáticos de empleados' },
          { separator: true },
          { label: 'Campo de Historial' },
          { separator: true },
          { label: 'Eliminar historiales' },
          { label: 'Eliminar historiales de empleados' },
        ],
      },
      {
        label: 'Asistencia',
        icon: 'fa-solid fa-calendar-check',
        items: [
          { label: 'Motivo de Ausentismo' },
          { label: 'Listado de motivos de ausentismos' },
          { separator: true },
          { label: 'Ausentismo' },
          { label: 'Listado de ausentismos' },
          { separator: true },
          { label: 'Presentismo' },
          { label: 'Presentismo Reloj' },
          { label: 'Listado de presentismos' },
          { separator: true },
          { label: 'Jornada Laboral' },
          { label: 'Listado de Jornadas Laborales' },
          { separator: true },
          { label: 'Feriado' },
        ],
      },
      {
        label: 'Informes',
        icon: 'fa-solid fa-chart-bar',
        items: [
          { label: 'Recibos de Sueldo' },
          { label: 'Libro de Sueldos' },
          { label: 'Diseño de Recibos de Sueldo' },
          { label: 'Diseño de Libro de Sueldos' },
          { separator: true },
          { label: 'Recibos Agrupados por Período' },
          { label: 'Recibos Agrupados por Empleado' },
          { separator: true },
          { label: 'Remuneración por Conceptos' },
          { label: 'Remuneración por Empleados' },
          { label: 'Remuneración por Grupos' },
          { separator: true },
          { label: 'Conceptos por Grupos' },
          { label: 'Conceptos Acumulados' },
          { label: 'Conceptos por Empleado' },
          { label: 'Conceptos por Recibo' },
          { separator: true },
          { label: 'Informes Personalizados' },
          { label: 'Diseño de Informes Personalizados' },
          { separator: true },
          { label: 'Acumulado de Novedades' },
          { label: 'Historial Acumulado por Días' },
          { separator: true },
          { label: 'Ausentismo Mensual' },
          { label: 'Ausentismo Mensual Empleados' },
          { label: 'Porcentaje de Ausentismo Mensual' },
          { label: 'Cantidad de Horas Trabajadas' },
        ],
      },
      {
        label: 'Exportación',
        icon: 'fa-solid fa-file-export',
        items: [
          { label: 'Exportación de Archivos' },
          { label: 'Formato de Exportación de Archivos' },
          { separator: true },
          { label: 'Importación de Novedades' },
          { label: 'Formato de Importación de Novedades' },
          { label: 'Importación de Empleados de AFIP' },
          { separator: true },
          { label: 'Exportación de Asientos a Contabilidad' },
          { label: 'Fórmula de Asiento' },
          { separator: true },
          { label: 'Exportación de Conceptos' },
          { label: 'Exportación de Fórmulas' },
          { label: 'Exportación de Convenios' },
          { label: 'Exportación de Grupo de Conceptos' },
          { label: 'Exportación de Tablas de Conceptos' },
          { separator: true },
          { label: 'Actualización de Sueldos' },
          { label: 'Exportación de Tablas' },
        ],
      },
    ],
  },
  {
    id: 'iva',
    label: 'I.V.A.',
    icon: 'fa-solid fa-percent',
    menu: [],
  },
];

export const ADMIN_MODULES = [
  {
    id: 'ayuda',
    label: 'Ayuda',
    icon: 'fa-solid fa-circle-question',
    path: '/ayuda',
    menu: [],
  },
  {
    id: 'configuracion',
    label: 'Config.',
    icon: 'fa-solid fa-gear',
    menu: [
      {
        label: 'Empresas',
        icon: 'fa-solid fa-building',
        items: [
          { label: 'Administrar empresas', icon: 'fa-solid fa-list', path: '/configuracion/empresas' },
        ],
      },
      {
        label: 'Tablas Generales',
        icon: 'fa-solid fa-table',
        items: [
          { label: 'Convenios', icon: 'fa-solid fa-file-contract', path: '/configuracion/convenios' },
          { separator: true },
          { label: 'Obras Sociales', icon: 'fa-solid fa-heart-pulse', path: '/configuracion/obras-sociales' },
          { separator: true },
          { label: 'Sindicatos', icon: 'fa-solid fa-people-group', path: '/configuracion/sindicatos' },
          { separator: true },
          {
            label: 'Tablas Comunes',
            icon: 'fa-solid fa-globe',
            items: [
              { label: 'Moneda', icon: 'fa-solid fa-coins', path: '/configuracion/comunes/monedas' },
              { label: 'Localidad', icon: 'fa-solid fa-location-dot', path: '/configuracion/comunes/localidades' },
              { label: 'País', icon: 'fa-solid fa-flag', path: '/configuracion/comunes/paises' },
              { label: 'Proyectos', icon: 'fa-solid fa-diagram-project', path: '/configuracion/comunes/proyectos' },
            ],
          },
          { separator: true },
          {
            label: 'Tablas ARCA',
            icon: 'fa-solid fa-landmark',
            items: [
              { label: 'Situación de Revista', path: '/configuracion/afip/situacion-revista' },
              { label: 'Condición', path: '/configuracion/afip/condicion-laboral' },
              { label: 'Actividad', path: '/configuracion/afip/actividad-laboral' },
              { label: 'Modalidad de Contratación', path: '/configuracion/afip/modalidad-contrato' },
              { label: 'Incapacidad', path: '/configuracion/afip/incapacidad' },
              { label: 'Código de Zona', path: '/configuracion/afip/codigo-zona' },
            ],
          },
        ],
      },
    ],
  },
];
