export const MODULES = [
  {
    id: 'contabilidad',
    label: 'Contabilidad',
    icon: 'fa-solid fa-book-open',
    menu: [
      {
        label: 'Cuentas',
        icon: 'fa-solid fa-sitemap',
        items: [
          { label: 'Plan de Cuentas', icon: 'fa-solid fa-sitemap', path: '/contabilidad/plan-cuentas' },
          { label: 'Listado de Cuentas', icon: 'fa-solid fa-list', path: '/contabilidad/cuentas' },
          { separator: true },
          { label: 'Centros de Costo', icon: 'fa-solid fa-layer-group', path: '/contabilidad/centros-costo' },
          { label: 'Leyendas', icon: 'fa-solid fa-quote-right', path: '/contabilidad/leyendas' },
        ],
      },
      {
        label: 'Ejercicios',
        icon: 'fa-solid fa-table-cells',
        items: [
          { label: 'Ejercicios', icon: 'fa-solid fa-table-cells', path: '/contabilidad/ejercicios' },
        ],
      },
      {
        label: 'Asientos',
        icon: 'fa-solid fa-scale-balanced',
        items: [
          { label: 'Listado de Asientos', icon: 'fa-solid fa-file-invoice', path: '/contabilidad/asientos' },
          { label: 'Unión de Asientos', icon: 'fa-solid fa-code-merge', path: '/contabilidad/union-asientos' },
          { separator: true },
          { label: 'Renumeración de Asientos', icon: 'fa-solid fa-arrow-down-1-9', path: '/contabilidad/asientos-renumeracion' },
          { label: 'Asientos Modelo', icon: 'fa-solid fa-copy', path: '/contabilidad/asientos-modelo' },
          { label: 'Asientos Desbalanceados', icon: 'fa-solid fa-scale-unbalanced', path: '/contabilidad/asientos-desbalanceados' },
        ],
      },
      {
        label: 'Informes',
        icon: 'fa-solid fa-chart-column',
        items: [
          { label: 'Mayor de Cuentas', icon: 'fa-solid fa-book', path: '/contabilidad/informes/mayor-cuentas' },
          { label: 'Balance General', icon: 'fa-solid fa-sitemap', path: '/contabilidad/informes/balance-general' },
          { label: 'Balance de Sumas y Saldos', icon: 'fa-solid fa-scale-balanced', path: '/contabilidad/informes/balance-sumas-saldos' },
          { label: 'Libro Diario', icon: 'fa-solid fa-file-invoice', path: '/contabilidad/asientos' },
          { label: 'Libro Diario Acumulado', icon: 'fa-solid fa-layer-group', path: '/contabilidad/informes/libro-diario-acumulado' },
          { separator: true },
          { label: 'Libro de Centros de Costo', icon: 'fa-solid fa-layer-group', path: '/contabilidad/informes/libro-centros-costo' },
          { label: 'Balance de Centros de Costo', icon: 'fa-solid fa-scale-balanced', path: '/contabilidad/informes/balance-centros-costo' },
        ],
      },
    ],
  },
  {
    id: 'sueldos',
    label: 'Sueldos',
    icon: 'fa-solid fa-briefcase',
    menu: [
      {
        label: 'Empleados',
        icon: 'fa-solid fa-users',
        items: [
          { label: 'Empleados activos', icon: 'fa-solid fa-user', path: '/sueldos/empleados' },
          { label: 'Empleados inactivos', icon: 'fa-solid fa-user-slash', path: '/sueldos/empleados?estado=inactivo' },
        ],
      },
      {
        label: 'Conceptos',
        icon: 'fa-solid fa-tags',
        items: [
          { label: 'Conceptos de liquidación', icon: 'fa-solid fa-tag', path: '/sueldos/conceptos' },
          { separator: true },
          { label: 'Fórmulas', icon: 'fa-solid fa-flask', path: '/sueldos/conceptos/formulas' },
          { separator: true },
          { label: 'Grupos de conceptos', icon: 'fa-solid fa-layer-group', path: '/sueldos/conceptos/grupos' },
          { label: 'Grupo general de conceptos', icon: 'fa-solid fa-earth-americas', path: '/sueldos/conceptos/general' },
          { label: 'Clases de concepto', icon: 'fa-solid fa-lock', path: '/sueldos/conceptos/clases' },
          { separator: true },
          { label: 'Tablas', icon: 'fa-solid fa-table', path: '/sueldos/conceptos/tablas' },
          { label: 'Tipos de tabla', icon: 'fa-solid fa-table-cells', path: '/sueldos/conceptos/tipos-tabla' },
        ],
      },
      {
        label: 'Liquidaciones',
        icon: 'fa-solid fa-calculator',
        items: [
          { label: 'Liquidaciones', icon: 'fa-solid fa-calendar-days', path: '/sueldos/liquidaciones' },
          { label: 'Nuevo Recibo', icon: 'fa-solid fa-file-invoice-dollar', path: '/sueldos/liquidaciones/recibo' },
          { label: 'Recibos Automáticos', icon: 'fa-solid fa-bolt', path: '/sueldos/liquidaciones/recibos-automaticos' },
          { label: 'Recibos Recalculados', icon: 'fa-solid fa-rotate', path: '/sueldos/liquidaciones/recibos-recalculados' },
          { separator: true },
          { label: 'Listado de recibos', icon: 'fa-solid fa-list', path: '/sueldos/liquidaciones/recibos' },
          { label: 'Listado de contribuciones', icon: 'fa-solid fa-building-columns', path: '/sueldos/liquidaciones/contribuciones' },
          { label: 'Listado de auxiliares', icon: 'fa-solid fa-list-check', path: '/sueldos/liquidaciones/auxiliares' },
          { separator: true },
          { label: 'Eliminación masiva', icon: 'fa-solid fa-trash', path: '/sueldos/liquidaciones/eliminacion-masiva' },
        ],
      },
      {
        label: 'Novedades',
        icon: 'fa-solid fa-bell',
        items: [
          { label: 'Novedades', icon: 'fa-solid fa-bell', path: '/sueldos/novedades' },
          { separator: true },
          { label: 'Novedades por Tabla', icon: 'fa-solid fa-table', path: '/sueldos/novedades/por-tabla' },
          { label: 'Novedades Secuenciales', icon: 'fa-solid fa-list-check', path: '/sueldos/novedades/secuenciales' },
          { label: 'Novedades Automáticas', icon: 'fa-solid fa-bolt', path: '/sueldos/novedades/automaticas' },
          { separator: true },
          { label: 'Tipo de Novedad', icon: 'fa-solid fa-tags', path: '/sueldos/novedades/tipos' },
          { label: 'Eliminar novedades', icon: 'fa-solid fa-trash', path: '/sueldos/novedades/eliminar' },
        ],
      },
      {
        label: 'Historial',
        icon: 'fa-solid fa-clock-rotate-left',
        items: [
          { label: 'Historiales', icon: 'fa-solid fa-clock-rotate-left', path: '/sueldos/historial' },
          { separator: true },
          { label: 'Historiales de Empleado', icon: 'fa-solid fa-user-clock', path: '/sueldos/historial/empleado' },
          { label: 'Historiales Automáticos de empleados', icon: 'fa-solid fa-bolt', path: '/sueldos/historial/automaticos' },
          { separator: true },
          { label: 'Campo de Historial', icon: 'fa-solid fa-tags', path: '/sueldos/historial/campos' },
          { separator: true },
          { label: 'Eliminar historiales', icon: 'fa-solid fa-trash', path: '/sueldos/historial/eliminar' },
          { label: 'Eliminar historiales de empleados', icon: 'fa-solid fa-trash', path: '/sueldos/historial/empleado/eliminar' },
        ],
      },
      {
        label: 'Asistencia',
        icon: 'fa-solid fa-calendar-check',
        items: [
          { label: 'Motivos de Ausentismo', icon: 'fa-solid fa-file-circle-exclamation', path: '/sueldos/asistencia/motivos-ausentismo' },
          { separator: true },
          { label: 'Ausentismo', icon: 'fa-solid fa-user-slash', path: '/sueldos/asistencia/ausentismo' },
          { separator: true },
          { label: 'Presentismo', icon: 'fa-solid fa-clock', path: '/sueldos/asistencia/presentismo' },
          { label: 'Presentismo Reloj', icon: 'fa-solid fa-stopwatch' },
          { separator: true },
          { label: 'Jornada Laboral', icon: 'fa-solid fa-calendar-week', path: '/sueldos/asistencia/jornada-laboral' },
          { separator: true },
          { label: 'Feriado', icon: 'fa-solid fa-umbrella-beach', path: '/sueldos/asistencia/feriados' },
        ],
      },
      {
        label: 'Informes',
        icon: 'fa-solid fa-chart-bar',
        items: [
          { label: 'Recibos de Sueldo', icon: 'fa-solid fa-file-invoice-dollar', path: '/sueldos/informes/recibos-sueldo' },
          { label: 'Libro de Sueldos', icon: 'fa-solid fa-book', path: '/sueldos/informes/libro-sueldos' },
          {
            label: 'Diseño de Recibos y Libro',
            icon: 'fa-solid fa-pen-ruler',
            items: [
              { label: 'Diseño de Recibos de Sueldo', icon: 'fa-solid fa-file-pen', path: '/sueldos/informes/diseno-recibos-sueldo' },
              { label: 'Diseño de Libro de Sueldos', icon: 'fa-solid fa-book-open', path: '/sueldos/informes/diseno-libro-sueldos' },
            ],
          },
          { separator: true },
          {
            label: 'Recibos Agrupados',
            icon: 'fa-solid fa-calendar-days',
            items: [
              { label: 'Recibos Agrupados por Período', icon: 'fa-solid fa-calendar-days', path: '/sueldos/informes/recibos-agrupados-periodo' },
              { label: 'Recibos Agrupados por Empleado', icon: 'fa-solid fa-user-clock', path: '/sueldos/informes/recibos-agrupados-empleado' },
            ],
          },
          { separator: true },
          {
            label: 'Remuneración',
            icon: 'fa-solid fa-sack-dollar',
            items: [
              { label: 'Remuneración por Conceptos', icon: 'fa-solid fa-sack-dollar', path: '/sueldos/informes/remuneracion-por-conceptos' },
              { label: 'Remuneración por Empleados', icon: 'fa-solid fa-users', path: '/sueldos/informes/remuneracion-por-empleados' },
              { label: 'Remuneración por Grupos', icon: 'fa-solid fa-people-group', path: '/sueldos/informes/remuneracion-por-grupos' },
            ],
          },
          { separator: true },
          {
            label: 'Conceptos Agrupados',
            icon: 'fa-solid fa-layer-group',
            items: [
              { label: 'Conceptos por Grupos', icon: 'fa-solid fa-object-group', path: '/sueldos/informes/conceptos-por-grupo' },
              { label: 'Conceptos Acumulados', icon: 'fa-solid fa-sitemap', path: '/sueldos/informes/conceptos-acumulados' },
              { label: 'Conceptos por Empleado', icon: 'fa-solid fa-user-tag', path: '/sueldos/informes/conceptos-por-empleado' },
              { label: 'Conceptos por Recibo', icon: 'fa-solid fa-receipt', path: '/sueldos/informes/conceptos-por-recibo' },
            ],
          },
          { separator: true },
          { label: 'Informes Personalizados', icon: 'fa-solid fa-table-list', path: '/sueldos/informes/personalizados' },
          { label: 'Diseño de Informes Personalizados', icon: 'fa-solid fa-drafting-compass', path: '/sueldos/informes/diseno-personalizados' },
          { separator: true },
          {
            label: 'Acumulados',
            icon: 'fa-solid fa-clock-rotate-left',
            className: 'submenu-flip-up',
            items: [
              { label: 'Acumulado de Novedades', icon: 'fa-solid fa-bell' },
              { label: 'Historial Acumulado por Días', icon: 'fa-solid fa-calendar-days' },
            ],
          },
          { separator: true },
          {
            label: 'Asistencia',
            icon: 'fa-solid fa-calendar-check',
            className: 'submenu-flip-up',
            items: [
              { label: 'Ausentismo Mensual', icon: 'fa-solid fa-user-slash' },
              { label: 'Ausentismo Mensual Empleados', icon: 'fa-solid fa-users-slash' },
              { label: 'Porcentaje de Ausentismo Mensual', icon: 'fa-solid fa-percent' },
              { label: 'Cantidad de Horas Trabajadas', icon: 'fa-solid fa-business-time' },
            ],
          },
        ],
      },
      {
        label: 'Exportación',
        icon: 'fa-solid fa-file-export',
        items: [
          {
            label: 'Libro de Sueldos Digital (ARCA)',
            icon: 'fa-solid fa-landmark',
            className: 'submenu-flip-left',
            items: [
              { label: 'Archivo de Conceptos', icon: 'fa-solid fa-tags', path: '/sueldos/exportacion/lsd-conceptos' },
              { label: 'Archivo de Liquidación', icon: 'fa-solid fa-file-invoice-dollar', path: '/sueldos/exportacion/lsd-liquidacion' },
              { label: 'Topes Previsionales', icon: 'fa-solid fa-gauge-high', path: '/sueldos/exportacion/lsd-topes' },
            ],
          },
          { separator: true },
          {
            label: 'Archivos',
            icon: 'fa-solid fa-file-export',
            className: 'submenu-flip-left',
            items: [
              { label: 'Exportación de Archivos', icon: 'fa-solid fa-file-arrow-up' },
              { label: 'Formato de Exportación de Archivos', icon: 'fa-solid fa-file-lines' },
            ],
          },
          {
            label: 'Importación',
            icon: 'fa-solid fa-file-import',
            className: 'submenu-flip-left',
            items: [
              { label: 'Importación de Novedades', icon: 'fa-solid fa-bell' },
              { label: 'Formato de Importación de Novedades', icon: 'fa-solid fa-file-lines' },
              { label: 'Importación de Empleados de AFIP', icon: 'fa-solid fa-landmark' },
            ],
          },
          {
            label: 'Contabilidad',
            icon: 'fa-solid fa-book',
            className: 'submenu-flip-left',
            items: [
              { label: 'Exportación de Asientos a Contabilidad', icon: 'fa-solid fa-file-invoice' },
              { label: 'Fórmula de Asiento', icon: 'fa-solid fa-flask' },
            ],
          },
          {
            label: 'Conceptos y Tablas',
            icon: 'fa-solid fa-tags',
            className: 'submenu-flip-left',
            items: [
              { label: 'Exportación de Conceptos', icon: 'fa-solid fa-tag' },
              { label: 'Exportación de Fórmulas', icon: 'fa-solid fa-flask' },
              { label: 'Exportación de Convenios', icon: 'fa-solid fa-file-contract' },
              { label: 'Exportación de Grupo de Conceptos', icon: 'fa-solid fa-layer-group' },
              { label: 'Exportación de Tablas de Conceptos', icon: 'fa-solid fa-table' },
            ],
          },
          { separator: true },
          { label: 'Actualización de Sueldos', icon: 'fa-solid fa-money-bill-trend-up' },
          { label: 'Exportación de Tablas', icon: 'fa-solid fa-table' },
        ],
      },
    ],
  },
  {
    id: 'iva',
    label: 'I.V.A.',
    icon: 'fa-solid fa-percent',
    menu: [],
  },
];

export const ADMIN_MODULES = [
  {
    id: 'ayuda',
    label: 'Ayuda',
    icon: 'fa-solid fa-circle-question',
    path: '/ayuda',
    menu: [],
  },
  {
    id: 'configuracion',
    label: 'Config.',
    icon: 'fa-solid fa-gear',
    menu: [
      {
        label: 'Empresas',
        icon: 'fa-solid fa-building',
        items: [
          { label: 'Administrar empresas', icon: 'fa-solid fa-list', path: '/configuracion/empresas' },
          { label: 'Copiar Configuración', icon: 'fa-solid fa-copy', path: '/configuracion/empresas/copiar-configuracion' },
          { separator: true },
          {
            label: 'Copia de Seguridad',
            icon: 'fa-solid fa-database',
            items: [
              { label: 'Generar copia de seguridad', icon: 'fa-solid fa-download', path: '/configuracion/empresas/backup' },
              { label: 'Restaurar copia de seguridad', icon: 'fa-solid fa-upload', path: '/configuracion/empresas/backup' },
              { separator: true },
              { label: 'Copia de seguridad en la nube', icon: 'fa-solid fa-cloud-arrow-up' },
              { label: 'Programar copia de seguridad', icon: 'fa-solid fa-clock' },
            ],
          },
        ],
      },
      {
        label: 'Seguridad',
        icon: 'fa-solid fa-shield-halved',
        permisoModulo: 'seguridad',
        items: [
          { label: 'Usuarios', icon: 'fa-solid fa-user', path: '/configuracion/seguridad/usuarios' },
          { label: 'Grupos', icon: 'fa-solid fa-user-group', path: '/configuracion/seguridad/grupos' },
          { label: 'Permisos', icon: 'fa-solid fa-key', path: '/configuracion/seguridad/permisos' },
          { separator: true },
          { label: 'Sesiones', icon: 'fa-solid fa-clock-rotate-left', path: '/configuracion/seguridad/sesiones' },
        ],
      },
      {
        label: 'Tablas Generales',
        icon: 'fa-solid fa-table',
        items: [
          { label: 'Convenios', icon: 'fa-solid fa-file-contract', path: '/configuracion/convenios' },
          { separator: true },
          { label: 'Obras Sociales', icon: 'fa-solid fa-heart-pulse', path: '/configuracion/obras-sociales' },
          { separator: true },
          { label: 'Sindicatos', icon: 'fa-solid fa-people-group', path: '/configuracion/sindicatos' },
          { separator: true },
          {
            label: 'Tablas Comunes',
            icon: 'fa-solid fa-globe',
            items: [
              { label: 'Moneda', icon: 'fa-solid fa-coins', path: '/configuracion/comunes/monedas' },
              { label: 'Localidad', icon: 'fa-solid fa-location-dot', path: '/configuracion/comunes/localidades' },
              { label: 'País', icon: 'fa-solid fa-flag', path: '/configuracion/comunes/paises' },
              { label: 'Proyectos', icon: 'fa-solid fa-diagram-project', path: '/configuracion/comunes/proyectos' },
            ],
          },
          { separator: true },
          {
            label: 'Tablas ARCA',
            icon: 'fa-solid fa-landmark',
            items: [
              { label: 'Situación de Revista', path: '/configuracion/afip/situacion-revista' },
              { label: 'Condición', path: '/configuracion/afip/condicion-laboral' },
              { label: 'Actividad', path: '/configuracion/afip/actividad-laboral' },
              { label: 'Modalidad de Contratación', path: '/configuracion/afip/modalidad-contrato' },
              { label: 'Incapacidad', path: '/configuracion/afip/incapacidad' },
              { label: 'Código de Zona', path: '/configuracion/afip/codigo-zona' },
            ],
          },
        ],
      },
    ],
  },
];
