export const MODULES = [
  {
    id: 'contabilidad',
    label: 'Contabilidad',
    icon: 'fa-solid fa-book-open',
    menu: [],
  },
  {
    id: 'sueldos',
    label: 'Sueldos',
    icon: 'fa-solid fa-briefcase',
    menu: [
      {
        label: 'Empleados',
        icon: 'fa-solid fa-users',
        items: [
          { label: 'Empleados activos', icon: 'fa-solid fa-user', path: '/sueldos/empleados' },
          { label: 'Empleados inactivos', icon: 'fa-solid fa-user-slash', path: '/sueldos/empleados?estado=inactivo' },
        ],
      },
      {
        label: 'Conceptos',
        icon: 'fa-solid fa-tags',
        items: [
          { label: 'Conceptos de liquidación', icon: 'fa-solid fa-tag', path: '/sueldos/conceptos' },
          { separator: true },
          { label: 'Fórmulas', icon: 'fa-solid fa-flask', path: '/sueldos/conceptos/formulas' },
          { separator: true },
          { label: 'Grupos de conceptos', icon: 'fa-solid fa-layer-group', path: '/sueldos/conceptos/grupos' },
          { label: 'Grupo general de conceptos', icon: 'fa-solid fa-earth-americas', path: '/sueldos/conceptos/general' },
          { label: 'Clases de concepto', icon: 'fa-solid fa-lock', path: '/sueldos/conceptos/clases' },
          { separator: true },
          { label: 'Tablas', icon: 'fa-solid fa-table', path: '/sueldos/conceptos/tablas' },
          { label: 'Tipos de tabla', icon: 'fa-solid fa-table-cells', path: '/sueldos/conceptos/tipos-tabla' },
        ],
      },
      {
        label: 'Liquidaciones',
        icon: 'fa-solid fa-calculator',
        items: [
          { label: 'Liquidaciones', icon: 'fa-solid fa-calendar-days', path: '/sueldos/liquidaciones' },
          { label: 'Nuevo Recibo', icon: 'fa-solid fa-file-invoice-dollar', path: '/sueldos/liquidaciones/recibo' },
          { label: 'Recibos Automáticos', icon: 'fa-solid fa-bolt', path: '/sueldos/liquidaciones/recibos-automaticos' },
          { label: 'Recibos Recalculados', icon: 'fa-solid fa-rotate', path: '/sueldos/liquidaciones/recibos-recalculados' },
          { separator: true },
          { label: 'Listado de recibos', icon: 'fa-solid fa-list', path: '/sueldos/liquidaciones/recibos' },
          { label: 'Listado de contribuciones', icon: 'fa-solid fa-building-columns', path: '/sueldos/liquidaciones/contribuciones' },
          { label: 'Listado de auxiliares', icon: 'fa-solid fa-list-check', path: '/sueldos/liquidaciones/auxiliares' },
          { separator: true },
          { label: 'Eliminación masiva', icon: 'fa-solid fa-trash', path: '/sueldos/liquidaciones/eliminacion-masiva' },
        ],
      },
      {
        label: 'Novedades',
        icon: 'fa-solid fa-bell',
        items: [
          { label: 'Novedades', icon: 'fa-solid fa-bell', path: '/sueldos/novedades' },
          { separator: true },
          { label: 'Novedades por Tabla', icon: 'fa-solid fa-table', path: '/sueldos/novedades/por-tabla' },
          { label: 'Novedades Secuenciales', icon: 'fa-solid fa-list-check', path: '/sueldos/novedades/secuenciales' },
          { label: 'Novedades Automáticas', icon: 'fa-solid fa-bolt', path: '/sueldos/novedades/automaticas' },
          { separator: true },
          { label: 'Tipo de Novedad', icon: 'fa-solid fa-tags', path: '/sueldos/novedades/tipos' },
          { label: 'Eliminar novedades', icon: 'fa-solid fa-trash', path: '/sueldos/novedades/eliminar' },
        ],
      },
      {
        label: 'Historial',
        icon: 'fa-solid fa-clock-rotate-left',
        items: [
          { label: 'Historiales', icon: 'fa-solid fa-clock-rotate-left', path: '/sueldos/historial' },
          { separator: true },
          { label: 'Historiales de Empleado', icon: 'fa-solid fa-user-clock', path: '/sueldos/historial/empleado' },
          { label: 'Historiales Automáticos de empleados', icon: 'fa-solid fa-bolt', path: '/sueldos/historial/automaticos' },
          { separator: true },
          { label: 'Campo de Historial', icon: 'fa-solid fa-tags', path: '/sueldos/historial/campos' },
          { separator: true },
          { label: 'Eliminar historiales', icon: 'fa-solid fa-trash', path: '/sueldos/historial/eliminar' },
          { label: 'Eliminar historiales de empleados', icon: 'fa-solid fa-trash', path: '/sueldos/historial/empleado/eliminar' },
        ],
      },
      {
        label: 'Asistencia',
        icon: 'fa-solid fa-calendar-check',
        items: [
          { label: 'Motivos de Ausentismo', icon: 'fa-solid fa-file-circle-exclamation', path: '/sueldos/asistencia/motivos-ausentismo' },
          { separator: true },
          { label: 'Ausentismo', icon: 'fa-solid fa-user-slash', path: '/sueldos/asistencia/ausentismo' },
          { separator: true },
          { label: 'Presentismo', icon: 'fa-solid fa-clock', path: '/sueldos/asistencia/presentismo' },
          { label: 'Presentismo Reloj', icon: 'fa-solid fa-stopwatch' },
          { separator: true },
          { label: 'Jornada Laboral', icon: 'fa-solid fa-calendar-week', path: '/sueldos/asistencia/jornada-laboral' },
          { separator: true },
          { label: 'Feriado', icon: 'fa-solid fa-umbrella-beach', path: '/sueldos/asistencia/feriados' },
        ],
      },
      {
        label: 'Informes',
        icon: 'fa-solid fa-chart-bar',
        items: [
          { label: 'Recibos de Sueldo' },
          { label: 'Libro de Sueldos' },
          { label: 'Diseño de Recibos de Sueldo' },
          { label: 'Diseño de Libro de Sueldos' },
          { separator: true },
          { label: 'Recibos Agrupados por Período' },
          { label: 'Recibos Agrupados por Empleado' },
          { separator: true },
          { label: 'Remuneración por Conceptos' },
          { label: 'Remuneración por Empleados' },
          { label: 'Remuneración por Grupos' },
          { separator: true },
          { label: 'Conceptos por Grupos' },
          { label: 'Conceptos Acumulados' },
          { label: 'Conceptos por Empleado' },
          { label: 'Conceptos por Recibo' },
          { separator: true },
          { label: 'Informes Personalizados' },
          { label: 'Diseño de Informes Personalizados' },
          { separator: true },
          { label: 'Acumulado de Novedades' },
          { label: 'Historial Acumulado por Días' },
          { separator: true },
          { label: 'Ausentismo Mensual' },
          { label: 'Ausentismo Mensual Empleados' },
          { label: 'Porcentaje de Ausentismo Mensual' },
          { label: 'Cantidad de Horas Trabajadas' },
        ],
      },
      {
        label: 'Exportación',
        icon: 'fa-solid fa-file-export',
        items: [
          { label: 'Exportación de Archivos' },
          { label: 'Formato de Exportación de Archivos' },
          { separator: true },
          { label: 'Importación de Novedades' },
          { label: 'Formato de Importación de Novedades' },
          { label: 'Importación de Empleados de AFIP' },
          { separator: true },
          { label: 'Exportación de Asientos a Contabilidad' },
          { label: 'Fórmula de Asiento' },
          { separator: true },
          { label: 'Exportación de Conceptos' },
          { label: 'Exportación de Fórmulas' },
          { label: 'Exportación de Convenios' },
          { label: 'Exportación de Grupo de Conceptos' },
          { label: 'Exportación de Tablas de Conceptos' },
          { separator: true },
          { label: 'Actualización de Sueldos' },
          { label: 'Exportación de Tablas' },
        ],
      },
    ],
  },
  {
    id: 'iva',
    label: 'I.V.A.',
    icon: 'fa-solid fa-percent',
    menu: [],
  },
];

export const ADMIN_MODULES = [
  {
    id: 'ayuda',
    label: 'Ayuda',
    icon: 'fa-solid fa-circle-question',
    path: '/ayuda',
    menu: [],
  },
  {
    id: 'configuracion',
    label: 'Config.',
    icon: 'fa-solid fa-gear',
    menu: [
      {
        label: 'Empresas',
        icon: 'fa-solid fa-building',
        items: [
          { label: 'Administrar empresas', icon: 'fa-solid fa-list', path: '/configuracion/empresas' },
        ],
      },
      {
        label: 'Tablas Generales',
        icon: 'fa-solid fa-table',
        items: [
          { label: 'Convenios', icon: 'fa-solid fa-file-contract', path: '/configuracion/convenios' },
          { separator: true },
          { label: 'Obras Sociales', icon: 'fa-solid fa-heart-pulse', path: '/configuracion/obras-sociales' },
          { separator: true },
          { label: 'Sindicatos', icon: 'fa-solid fa-people-group', path: '/configuracion/sindicatos' },
          { separator: true },
          {
            label: 'Tablas Comunes',
            icon: 'fa-solid fa-globe',
            items: [
              { label: 'Moneda', icon: 'fa-solid fa-coins', path: '/configuracion/comunes/monedas' },
              { label: 'Localidad', icon: 'fa-solid fa-location-dot', path: '/configuracion/comunes/localidades' },
              { label: 'País', icon: 'fa-solid fa-flag', path: '/configuracion/comunes/paises' },
              { label: 'Proyectos', icon: 'fa-solid fa-diagram-project', path: '/configuracion/comunes/proyectos' },
            ],
          },
          { separator: true },
          {
            label: 'Tablas ARCA',
            icon: 'fa-solid fa-landmark',
            items: [
              { label: 'Situación de Revista', path: '/configuracion/afip/situacion-revista' },
              { label: 'Condición', path: '/configuracion/afip/condicion-laboral' },
              { label: 'Actividad', path: '/configuracion/afip/actividad-laboral' },
              { label: 'Modalidad de Contratación', path: '/configuracion/afip/modalidad-contrato' },
              { label: 'Incapacidad', path: '/configuracion/afip/incapacidad' },
              { label: 'Código de Zona', path: '/configuracion/afip/codigo-zona' },
            ],
          },
        ],
      },
    ],
  },
];
